apiVersion: v1
kind: Service
metadata:
  name: aerospike-operator-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "aerospike-kubernetes-operator.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    {{- with .Values.webhookService.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  {{- with .Values.webhookService.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webhookService.type | quote }}
  selector:
    # Specified by the deployment/pod
    app: {{ template "aerospike-kubernetes-operator.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    {{- with .Values.podLabels }}{{ toYaml . | nindent 4 }}{{ end }}
    {{- with .Values.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  ports:
    - port: {{ .Values.webhookService.port }}
      # Can be the name of port 9443 of the container
      targetPort: {{ .Values.webhookService.targetPort  }}
      protocol: TCP
